title: Brewsoc Knowledge Base
description: Knowledge base curated by the Brewsoc community
theme: just-the-docs

url: https://resources.brewsoc.com

plugins:
    - jekyll-default-layout

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template