title: Brewsoc Knowledge Base
description: Knowledge base curated by the Brewsoc community
theme: just-the-docs

url: https://brewsoc.github.io/resources

aux_links:
    Template Repository: https://github.com/just-the-docs/just-the-docs-template