title: Brewsoc Knowledgebase
description: A knowledge base curated by the brewsoc community
theme: just-the-docs

url: https://resources.brewsoc.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template