title: Brewsoc Knowledge Base
description: A knowledge base curated by the brewsoc community
theme: just-the-docs
footer_content: "Content co-authored with ChatGPT"
url: https://resources.brewsoc.com
